# .readthedocs.yaml

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# 在这里加入自定义的构建命令
commands:
  - python generate_robots.py  # 执行生成 robots.txt 的脚本
  - mkdocs build  # 然后执行 MkDocs 构建命令
# 这样就可以使用mkdocs的主题了
mkdocs:
  configuration: mkdocs.yml  # MkDocs 配置文件路径

# 构建格式
#pdf 依赖的库往往不好用。不用pdf
#formats:
#  - pdf

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

python:
  # 在这里填写mkdocs的主题了
  install:
   - requirements: requirements.txt

