# .readthedocs.yaml
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# 安装依赖项
python:
  install:
    - requirements: requirements.txt  # 确保 mkdocs 和其他依赖被正确安装

# 配置构建步骤
commands:
  - pip install -r requirements.txt  # 安装所有依赖
  - python generate_robots.py  # 执行生成 robots.txt 的脚本
  - mkdocs build  # 执行 mkdocs 构建命令
