# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: conf.py

# Build formats (pdf, epub, htmlzip)
formats: []

# Python configuration
python:
  install:
    - requirements: requirements.txt

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
