# 只要当前的remote 仓库是github的, push page就能自动推到github
#
#site_url: https://wzrydoc.readthedocs.io/
#site_url: https://cndaqiang.github.io/wzry.doc/
site_url: https://wzry-doc.pages.dev/
# 这个url决定了sitemap.xml中的地址，如果不设置, git page上显示的sitemap.xml里面就是空的，设置了就被强制替换为了这个
# 此外，设置后本地预览的网址总是带一个/wzry.doc/，除了双配置文件，解决不了，不解决了
#
site_name: WZRY.doc
site_author: cndaqiang
copyright: Copyright &copy; 2024 cndaqiang
dev_addr: '0.0.0.0:8000'

#
# 主题右上角显示的repo地址，可以设置为开源项目地址
repo_url: https://github.com/cndaqiang/WZRY
repo_name: 'cndaqiang/WZRY' # 只是右上角显示的文字内容

nav:
    - 项目介绍: index.md
    - 使用手册:
      - 安装指南: guide/install.md
      - 配置文件: guide/config.md
      - 高级功能: guide/file.md
      - "&nbsp;■&nbsp;对战模式": guide/duizhanmoshi.md
      - "&nbsp;■&nbsp;礼包功能": guide/libao.md
      - "&nbsp;■&nbsp;选择英雄": guide/shuliandu.md
      - "&nbsp;■&nbsp;图片更新": guide/tupiangengxin.md
      - 组队教程: guide/zudui.md
      - 更新资源: guide/upfig.md
      - 图文教程: guide/tuwen.md
    - 常见问题: QA.md
    - 提出问题: https://github.com/cndaqiang/WZRY/issues
    - 经验分享: 
      - 战令经验最大化: exp/zhanling.md
      - 模拟器推荐: exp/moniqi.md
      - 多账户使用同一个控制文件: exp/link.md
      - 我在用的控制文件: exp/duizhanmoshi.md
      - 在docker内干农活: exp/docker.md
      - 控制苹果手机: https://cndaqiang.github.io/2023/11/10/MobileAuto/
      - 定时执行脚本: exp/dingshi.md
      - 在任意目录运行: exp/otherdir.md
    - 关于:
      - 更新日志: about/update.md
      - 许可: about/license.md


# markdown拓展语法
markdown_extensions:
  - admonition #MkDocs 警告框，!!!note 语法https://lifeinzucc.github.io/help/markdown/admonition/
  - footnotes #脚注
  - codehilite # 代码高亮？
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  # 开启这个拓展，才能使用中文的标题生成各个标题的链接（锚点），进行跳转引用
  - toc: # 大纲
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify


theme:
#  name: gitbook
  name: material
  # 网站的logo, 直接填写文件名字对于不同的网站可能并不友好, 因为有些域名的url是doamin/xxx/Moba1.png, 直接写名字容易变为domaoin/Moba1, 无法识别到
  favicon: https://cndaqiang.github.io/wzry.doc/favicon.png
  #favicon: Moba1.png
  # 主题页面的log
  logo: https://cndaqiang.github.io/wzry.doc/favicon.png
  #logo: Moba1.png #favicon.ico
  icon:
    repo: fontawesome/brands/github
  # 引入自定义的js, 例如统计等信息、搜索引擎的站点认证
  custom_dir: overrides

extra:
  # https://mkdoc-material.llango.com/setup/setting-up-the-footer/
  # https://fontawesome.com/search?q=blog&o=r&f=classic
  social:
    # 镜像网站
    - icon: fontawesome/solid/cloud
      link: https://wzry-doc.pages.dev/
      name: cloudflare
    # 国内有墙
    #- icon: fontawesome/solid/server
    #  link: https://wzry-doc.serv00.net/
    #  name: serv00
    - icon: fontawesome/solid/lock
      link: https://wzrydoc.readthedocs.io
      name: untagged #readthedocs
    - icon: fontawesome/brands/github
      link: https://github.com/cndaqiang
      name: author
    - icon: fontawesome/brands/python
      link: https://github.com/cndaqiang/WZRY
      name: cndaqiang/WZRY
    - icon: fontawesome/solid/square-rss
      link: https://cndaqiang.github.io/wzry.doc/sitemap.xml
      name: rss
    - icon: fontawesome/solid/chart-area
      link: https://cloud.umami.is/share/YHbP7dG7wOyJTdBg/cndaqiang.github.io
      name: visitor
    - icon: fontawesome/solid/earth-africa
      link: https://www.revolvermaps.com/livestats/map/5hik3848fwe/
      name: visitor
  # material带的google统计,https://analytics.google.com/ 不采用主题提供的,自己进行控制
  # analytics:
  #   provider: google
  #   property: GT-NM8H2HCW
# 自定义的脚本,可以通过extra_javascript引入, 也可以通过theme.custom_dir.overrides引入
# 下面是我适配的一些功能
  # google 统计的ID, 创建新账户、新媒体资源, 不然会和旧网站合并
  googleanalysisID: "G-FLH4L3Q02F"
  # 百度统计的ID
  baidutongjiID: "76d0fc6b8ffd3901ec51e8bece995b22"
  # umami统计
  umaniID: "1d2518ba-011c-47f7-bf3d-c2454778ef02"
  # revolvermaps 统计
  revolvermapsID: "5hik3848fwe"
  # 在这些域名不进行访客统计
  blocked_domains:
    - "0.0.0.0"
    - "127.0.0.1"
    - "localhost"
    - "wzry-doc.serv00.net" # 不追踪统计的域名
    - "wzrydoc.readthedocs.io" # 不追踪统计的域名
    - "example.com"  # 在这里添加您的域名

#extra_javascript:
  # 这些内容已移植overrides/main.html
  # baidutongji
  #- javascripts/baidu.tongji.js
  # 卜算子统计，可以，但是只能在md文件中填写 span id="busuanzi_value_site_pv"等纯html内容进行解析
  # - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
#
# 中文搜索
# https://cloud-atlas.readthedocs.io/zh-cn/latest/devops/docs/mkdocs/mkdocs_chinese_search.html
plugins:
  - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'