# 只要当前的remote 仓库是github的, push page就能自动推到github
#
#site_url: https://wzrydoc.readthedocs.io/
#site_url: https://cndaqiang.github.io/wzry.doc/
site_url: https://wzry-doc.pages.dev/
# 这个url决定了sitemap.xml中的地址，如果不设置, git page上显示的sitemap.xml里面就是空的，设置了就被强制替换为了这个
# 此外，设置后本地预览的网址总是带一个/wzry.doc/，除了双配置文件，解决不了，不解决了
#
site_name: WZRY.doc
site_author: cndaqiang
copyright: Copyright &copy; 2024 cndaqiang
#需要转换网站上的js到本地，网页统计
extra_javascript:
  # umami 统计
  - javascripts/umami.tongji.js
  # 卜算子统计，可以，但是只能在md文件中填写 span id="busuanzi_value_site_pv"等纯html内容进行解析
  # - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

# 本地调试地址，本机可以访问各个ip, 局域网默认还是无法访问
dev_addr: '0.0.0.0:8000'

#
# 主题右上角显示的repo地址，可以设置为开源项目地址
repo_url: https://github.com/cndaqiang/WZRY
repo_name: 'cndaqiang/WZRY' # 只是右上角显示的文字内容
# repo的start信息，在gh的page上会显示，本地url不会显示。
#repo_name: cndaqiang/WZRY

nav:
    - 项目介绍: index.md
    - 使用手册:
      - 安装指南: guide/install.md
      - 配置文件: guide/config.md
      - 高级功能: guide/file.md
      - "&nbsp;■&nbsp;对战模式": guide/duizhanmoshi.md
      - "&nbsp;■&nbsp;礼包功能": guide/libao.md
      - "&nbsp;■&nbsp;选择英雄": guide/shuliandu.md
      - 组队教程: guide/zudui.md
      - 更新资源: guide/upfig.md
      - 图文教程: guide/tuwen.md
    - 常见问题: QA.md
    - 提出问题: https://github.com/cndaqiang/WZRY/issues
    - 经验分享: 
      - 战令: exp/zhanling.md
      - 模拟器: exp/moniqi.md
      - 多账户使用同一个控制文件: exp/link.md
      - 我在用的控制文件: exp/duizhanmoshi.md
      - 怎么控制苹果手机: https://cndaqiang.github.io/2023/11/10/MobileAuto/
      - 定时执行脚本: exp/dingshi.md
    - 关于:
      - 更新日志: about/update.md
      - 许可: about/license.md
theme:
#  name: gitbook
  name: material
  # 网站的logo
  favicon: fig/favicon.jpg
  # 主题页面的log
  logo: favicon.ico
  icon:
    repo: fontawesome/brands/github
  # 引入百度的验证头 meta
  custom_dir: overrides


# markdown拓展语法
markdown_extensions:
  - admonition #MkDocs 警告框，!!!note 语法https://lifeinzucc.github.io/help/markdown/admonition/
  - footnotes #脚注
  - codehilite # 代码高亮？
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  # 开启这个拓展，才能使用中文的标题生成各个标题的链接（锚点），进行跳转引用
  - toc: # 大纲
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify



extra:
  # https://mkdoc-material.llango.com/setup/setting-up-the-footer/
  # https://fontawesome.com/search?q=blog&o=r&f=classic
  social:
    # 镜像网站
    - icon: fontawesome/solid/cloud
      link: https://wzry-doc.pages.dev/
      name: mirror
    - icon: fontawesome/solid/book
      link: https://wzrydoc.rtfd.io
      name: mirror-doc
    - icon: fontawesome/brands/github
      link: https://github.com/cndaqiang
      name: author
    - icon: fontawesome/brands/python
      link: https://github.com/cndaqiang/WZRY
      name: cndaqiang/WZRY
    - icon: fontawesome/solid/square-rss
      link: https://cndaqiang.github.io/wzry.doc/sitemap.xml
      name: rss
    - icon: fontawesome/solid/chart-area
      link: https://cloud.umami.is/share/YHbP7dG7wOyJTdBg/cndaqiang.github.io
      name: visitor


  analytics:
    provider: google
    property: G-7G7TFCTQJY
#    property: UA-109057291-1
#G-7G7TFCTQJY

# 中文搜索
# https://cloud-atlas.readthedocs.io/zh-cn/latest/devops/docs/mkdocs/mkdocs_chinese_search.html
plugins:
  - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'